
<?php
	require_once("cabecera.inc");
?>


	<div class="row jumbotron center ">
		<h1>Página principal de mi molona red social</h1>
	</div>

	<!--
	<?php 
	if($_SESSION['iduser'] == 1)
	{
	?>
	<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 divmargin">
		<p>El usuario <?php echo $nombre;?> se ha logado
		</p>
		</div>
	<?php
	}
	?>
	-->
	
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-3 divmargin">
			<p>Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-3 divmargin">
			<p>Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-3 divmargin">
			<p>Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-3 divmargin">
			<p>Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...</p>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-6 divmargin">
			<p>Noticia 1 de mi red social que habla de mis cosas ... 
			Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...</p>
		</div>
		<div class="col-xs-12 col-sm-6 divmargin">
			<p>Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...</p>
		</div>
		<div class="col-xs-12 col-sm-6 divmargin">
			<p>Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...
			Por este lado podríamos hablar del tiempo que hará mañana ...</p>
		</div>

		<div class="col-xs-12 col-sm-6 divmargin">
			<p>Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...
			Ultima actualización realizada por un usuario a mi red social que nos dice como ...</p>
		</div>
		<div class="col-xs-12 col-sm-6 divmargin">
			<p>Noticia 1 de mi red social que habla de mis cosas ... 
			Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...
			Noticia 1 de mi red social que habla de ...</p>
		</div>
	</div>

<?php
	require_once("pie.inc");
?>